import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import { BsInstagram, BsFacebook, BsLinkedin } from "react-icons/bs";

export default function Home() {
  const Router = useRouter();

  function toContactMe() {
    Router.push({
      pathname: "/contact",
    });
  }

  return (
    <div>
      <Head>
        <title>Skripsi</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
    </div>
  );
}
